# Generated by Django 6.0.7 on 2026-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_remove_constructionstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='localities/'),
        ),
    ]
