# Generated by Django 6.0.7 on 2026-09-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_followup_id_alter_meeting_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
