# Generated by Django 6.0.7 on 2026-09-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_amenities_amenities'),
        ('properties_utility', '0002_bank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties_utility.projectamenities'),
        ),
    ]
