# Generated by Django 6.0.7 on 2026-09-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_amenities'),
        ('properties_utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties_utility.amenity'),
        ),
    ]
