# Generated by Django 6.0.7 on 2026-09-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_amenities_amenities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
