# Generated by Django 6.0.7 on 2026-09-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_delete_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity', to='properties.project'),
        ),
    ]
