# Generated by Django 6.0.7 on 2026-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_connectivity_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
