# Generated by Django

import django.db.models.deletion  # <-- YE LINE ADD KAREIN
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='project_amenities', 
                to='properties_utility.projectamenities'
            ),
        ),
    ]