# Generated by Django 6.0.7 on 2026-09-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_amenities'),
        ('properties_utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_amenities', to='properties_utility.projectamenities'),
        ),
    ]
