# Generated by Django 6.0.7 on 2026-09-09 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_about_content_alter_about_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('message', models.TextField(verbose_name='Message / Requirement')),
                ('schedule_visit', models.DateField(blank=True, null=True, verbose_name='Schedule Visit Date')),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('visit_scheduled', 'Site Visit Scheduled'), ('closed', 'Closed / Booked'), ('lost', 'Lost / Not Interested')], default='new', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Enquiry',
                'verbose_name_plural': 'Property Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
