# Generated by Django 6.0.7 on 2026-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propertyenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyenquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('visit_scheduled', 'Site Visit Scheduled'), ('closed', 'Closed / Booked'), ('lost', 'Lost / Not Interested')], default='new', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
