# Generated by Django 6.0.7 on 2026-09-10 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_propertyenquiry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_one_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_one_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_two_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='button_two_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_highlight',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='read_legacy',
        ),
        migrations.RemoveField(
            model_name='about',
            name='right_image1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='right_image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='about',
            name='rera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='square_feet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='happy_families',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.setting')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': '3. Milestones',
                'ordering': ['year'],
            },
        ),
    ]
