# Generated by Django 6.0.7 on 2026-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
